package com.soccer.tracker

/**
 * Build-time configuration constants.
 *
 * In a real project these would be generated by Gradle's ``BuildConfig``
 * or read from ``local.properties``.  Here we define them as a plain object
 * so the code compiles without a Gradle build step.
 */
object BuildConfig {
    /** Base URL for the FastAPI backend — override for different environments. */
    const val API_BASE_URL: String = "http://10.0.2.2:8000/"

    /** Debug flag — controls HTTP logging, crash reporting, etc. */
    const val DEBUG: Boolean = true
}
